extends AnimatedSprite2D
class_name MomPortraitAnimator

## MomPortraitAnimator
##
## Drives Mom's animated dialog portrait. Owns a small priority system:
##   REACTION (one-shot) > SPEAKING (mood-scaled loop) > IDLE (still + blink)
## One-shot reactions interrupt speech and return to the correct ground
## state (speech if the typewriter is still running, idle otherwise) via
## animation_finished. A blink Timer fires random idle blinks and occasional
## mood-appropriate fidgets. All sheets share frame 0 as the neutral base
## pose, so instant clip swaps read as continuous motion.
##
## Clips come from Resources/Art/Characters/Mom/mom_portrait_frames.tres,
## generated by Scripts/Editor/build_mom_spriteframes.gd.

signal reaction_finished(clip: StringName)

enum State { IDLE, SPEAKING, REACTING }
enum MoodState { HAPPY, NEUTRAL, ANNOYED, ANGRY, FURIOUS }
enum ReactionPriority { FIDGET, NORMAL, FORCED }

const FRAMES_PATH := "res://Resources/Art/Characters/Mom/mom_portrait_frames.tres"
const BLINK_MIN_INTERVAL := 2.0
const BLINK_MAX_INTERVAL := 6.0
## Chance a blink-timer tick fires a mood fidget instead of a blink.
const FIDGET_CHANCE := 0.10

## MoodState -> reaction clips allowed for fidgets and NORMAL requests.
## "laugh" is deliberately absent from angry states; it is still reachable
## there via FORCED (sarcastic laugh requested by dialog content).
const STATE_REACTIONS := {
	MoodState.HAPPY: [&"laugh"],
	MoodState.NEUTRAL: [&"eyeroll", &"shakehead"],
	MoodState.ANNOYED: [&"eyeroll", &"shakehead"],
	MoodState.ANGRY: [&"glare", &"shakehead"],
	MoodState.FURIOUS: [&"angryshake", &"glare"],
}

var _state: State = State.IDLE
var _mood: int = 5
var _expression_hint: String = ""
var _resume_speaking: bool = false
var _queued_reaction: StringName = &""
var _current_reaction: StringName = &""
var _paused: bool = false
var _blink_timer: Timer


func _ready() -> void:
	if sprite_frames == null:
		sprite_frames = load(FRAMES_PATH)
	if sprite_frames == null:
		push_error("[MomPortraitAnimator] Missing SpriteFrames: " + FRAMES_PATH)
		return
	if not animation_finished.is_connected(_on_animation_finished):
		animation_finished.connect(_on_animation_finished)
	_blink_timer = Timer.new()
	_blink_timer.name = "BlinkTimer"
	_blink_timer.one_shot = true
	_blink_timer.timeout.connect(_on_blink_timer_timeout)
	add_child(_blink_timer)
	_swap_clip(&"idle")
	_restart_blink_timer()
	print("[MomPortraitAnimator] Initialized")


## set_mood(mood)
##
## Sets Mom's mood (0-10, higher = angrier). If she is currently talking,
## the speech clip swaps immediately (pop-free via shared frame-0 pose).
func set_mood(mood: int) -> void:
	_mood = clampi(mood, 0, 10)
	if _state == State.SPEAKING:
		_swap_clip(_speech_clip_for_state())


## get_mood_state() -> MoodState
##
## Maps the 0-10 mood onto the 5 animation states (merges Very Happy+Happy
## from ChoresManager's text bands).
func get_mood_state() -> MoodState:
	if _mood <= 4:
		return MoodState.HAPPY
	if _mood == 5:
		return MoodState.NEUTRAL
	if _mood <= 7:
		return MoodState.ANNOYED
	if _mood <= 9:
		return MoodState.ANGRY
	return MoodState.FURIOUS


## start_talking(expression_hint)
##
## Enters SPEAKING with the mood/expression-scaled speech loop. If a
## reaction is playing, speech resumes when it finishes instead.
func start_talking(expression_hint: String = "") -> void:
	if expression_hint != "":
		_expression_hint = expression_hint
	if _state == State.REACTING:
		_resume_speaking = true
		return
	_state = State.SPEAKING
	_swap_clip(_speech_clip_for_state())


## stop_talking()
##
## Called when the typewriter finishes. Returns to idle unless a reaction
## is still playing (it will land on idle when done).
func stop_talking() -> void:
	_resume_speaking = false
	if _state == State.SPEAKING:
		_state = State.IDLE
		_swap_clip(&"idle")


## play_reaction(clip, priority)
##
## Plays a one-shot reaction. FIDGET requests only fire from IDLE and are
## dropped otherwise. NORMAL requests must be available at the current
## mood state. FORCED bypasses availability (dialog-driven beats, e.g. a
## sarcastic laugh at high mood). While REACTING, further requests replace
## the queued reaction (queue depth 1). Interrupting SPEAKING sets a flag
## to resume speech when the reaction finishes.
func play_reaction(clip: StringName, priority: ReactionPriority = ReactionPriority.NORMAL) -> void:
	if _paused or not _frames_ready():
		return
	if priority == ReactionPriority.FIDGET:
		if _state != State.IDLE:
			return
	elif priority == ReactionPriority.NORMAL:
		if clip not in _available_reactions():
			return
	if not sprite_frames.has_animation(clip):
		push_warning("[MomPortraitAnimator] Unknown clip: %s" % clip)
		return
	if _state == State.REACTING:
		_queued_reaction = clip
		return
	if _state == State.SPEAKING:
		_resume_speaking = true
	_state = State.REACTING
	_current_reaction = clip
	_swap_clip(clip)


## react_to_tone(tone)
##
## Convenience for dialog responses: "sassy" draws a negative reaction
## (never a genuine laugh - falls back to a forced eyeroll in happy states),
## "polite" gets a laugh only from a happy Mom, "neutral" does nothing.
func react_to_tone(tone: String) -> void:
	match tone:
		"sassy":
			var pool: Array[StringName] = []
			for clip in _available_reactions():
				if clip != &"laugh":
					pool.append(clip)
			if pool.is_empty():
				play_reaction(&"eyeroll", ReactionPriority.FORCED)
			else:
				play_reaction(pool[randi() % pool.size()], ReactionPriority.NORMAL)
		"polite":
			if get_mood_state() == MoodState.HAPPY:
				play_reaction(&"laugh", ReactionPriority.NORMAL)


## set_expression_hint(expression_name)
##
## Stores the legacy dialog expression ("happy"/"neutral"/"upset") used to
## pick the speech clip. "upset" scales with real mood: ANNOYED at mood <= 4.
func set_expression_hint(expression_name: String) -> void:
	_expression_hint = expression_name.to_lower()
	if _state == State.SPEAKING:
		_swap_clip(_speech_clip_for_state())


## set_paused(paused)
##
## Halts the blink timer and playback while the dialog is hidden.
func set_paused(paused: bool) -> void:
	_paused = paused
	if _blink_timer == null:
		return
	if paused:
		_blink_timer.stop()
		stop()
	else:
		play()
		_restart_blink_timer()


func get_state() -> State:
	return _state


func _frames_ready() -> bool:
	return sprite_frames != null


func _available_reactions() -> Array[StringName]:
	var result: Array[StringName] = []
	result.assign(STATE_REACTIONS.get(get_mood_state(), []))
	return result


func _speech_clip_for_state() -> StringName:
	var state := get_mood_state()
	match _expression_hint:
		"happy":
			state = MoodState.HAPPY
		"upset":
			if _mood <= 4:
				state = MoodState.ANNOYED
			else:
				state = MoodState.ANGRY
		"neutral":
			state = MoodState.NEUTRAL
	match state:
		MoodState.HAPPY:
			return &"speech_happy"
		MoodState.NEUTRAL, MoodState.ANNOYED:
			return &"speech_normal"
	return &"speech_angry"


func _swap_clip(clip: StringName) -> void:
	if not _frames_ready():
		return
	if not sprite_frames.has_animation(clip):
		push_error("[MomPortraitAnimator] SpriteFrames missing clip: %s" % clip)
		return
	if animation == clip and is_playing():
		return
	play(clip)


func _on_animation_finished() -> void:
	var finished_clip := animation
	if _state == State.REACTING:
		if _queued_reaction != &"":
			var next_clip := _queued_reaction
			_queued_reaction = &""
			_current_reaction = next_clip
			_swap_clip(next_clip)
			return
		_current_reaction = &""
		if _resume_speaking:
			_state = State.SPEAKING
			_swap_clip(_speech_clip_for_state())
		else:
			_state = State.IDLE
			_swap_clip(&"idle")
		reaction_finished.emit(finished_clip)
	elif finished_clip == &"blink" and _state == State.IDLE:
		_swap_clip(&"idle")


func _on_blink_timer_timeout() -> void:
	if _state == State.IDLE and not _paused:
		if randf() < FIDGET_CHANCE and not _available_reactions().is_empty():
			var pool := _available_reactions()
			play_reaction(pool[randi() % pool.size()], ReactionPriority.FIDGET)
		else:
			_swap_clip(&"blink")
	_restart_blink_timer()


func _restart_blink_timer() -> void:
	if _blink_timer == null or _paused:
		return
	_blink_timer.wait_time = randf_range(BLINK_MIN_INTERVAL, BLINK_MAX_INTERVAL)
	_blink_timer.start()
